version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DATABASE_URL: postgresql://<user>:<password>@db:<port>/<db>
    ports:
      - "5432:5432"
  app:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://<user>:<password>@db:<port>/<db>
